LibraryManagementSystem/Controllers/CheckoutController.cs
using Application.Enums;
using Application.Interfaces;
using Application.Models;
using Application.ViewModels.Checkout;
using Application.ViewModels.Member;
using Infrastructure.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace LibraryManagementSystem.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly ICheckoutRepository _checkoutRepository;
        private readonly LibraryDbContext _libraryDbContext;
        private readonly UserManager<ApplicationUser> _userManager;



        public CheckoutController(ICheckoutRepository checkoutRepository , LibraryDbContext libraryDbContext , UserManager<ApplicationUser> userManager)
        {
            _checkoutRepository = checkoutRepository;
            _libraryDbContext = libraryDbContext;
            _userManager = userManager;

        }

        public async Task<IActionResult> Create()
        {
            var users = await _userManager.GetUsersInRoleAsync("Member");

            var viewModel = new AddCheckoutVM
            {
                Books = (await _checkoutRepository.GetBooksAsync()).Select(b => new SelectListItem
                {
                    Value = b.Id.ToString(),
                    Text = b.Name 
                }),
                BookCopies = Enumerable.Empty<SelectListItem>(),

                Users = users.Select(u => new SelectListItem
            {
                Value = u.Id,
               Text = u.UserName
                })

 
        };

            return View("AddCheckout", viewModel);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddCheckoutVM checkoutVM)
        {
            if (!ModelState.IsValid)
            {
                await PopulateDropdownsAsync(checkoutVM);

                var modelErrors = string.Join(", ", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
                ModelState.AddModelError(string.Empty, $"Please correct the following errors: {modelErrors}");
                return View("AddCheckout", checkoutVM);
            }

            try
            {
                await _checkoutRepository.AddCheckoutAsync(checkoutVM);
                await _checkoutRepository.MarkBookCopyAsUnavailableAsync(checkoutVM.BookCopyID);

                TempData["SuccessMessage"] = "Checkout created successfully!";
                await PopulateDropdownsAsync(checkoutVM); 

                return View("AddCheckout", checkoutVM); 
            }
            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                await PopulateDropdownsAsync(checkoutVM);
                return View("AddCheckout", checkoutVM);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request. Please try again.");
                ModelState.AddModelError(string.Empty, ex.Message); 
                await PopulateDropdownsAsync(checkoutVM);
                return View("AddCheckout", checkoutVM);
            }
        }

        private async Task PopulateDropdownsAsync(AddCheckoutVM checkoutVM)
        {
            checkoutVM.Books = (await _checkoutRepository.GetBooksAsync()).Select(b => new SelectListItem
            {
                Value = b.Id.ToString(),
                Text = b.Name
            });

            checkoutVM.BookCopies = (await _checkoutRepository.GetAvailableBookCopiesByBookIdAsync(checkoutVM.BookID))
                .Select(b => new SelectListItem
                {
                    Value = b.Id.ToString(),
                    Text = $"Copy ID: {b.Id}"
                });

            var users = await _userManager.GetUsersInRoleAsync("Member");
            checkoutVM.Users = users.Select(u => new SelectListItem
            {
                Value = u.Id,
                Text = u.UserName
            });

        }

        [HttpGet("api/bookcopies/{bookId}")]
        public async Task<IActionResult> GetAvailableBookCopiesByBookId(int bookId)
        {
            var bookCopies = await _checkoutRepository.GetAvailableBookCopiesByBookIdAsync(bookId);
            if (bookCopies == null)
            {
                return NotFound();
            }

            return Ok(bookCopies.Select(bc => new {
                id = bc.Id,
                bookName = bc.Book.Name 
            }));
        }

        public async Task<IActionResult> GetCheckouts(
         string searchUser,
         DateTime? searchDate,
         string searchBook,
         CheckoutStatus? SearchStatus,
         int pageNumber = 1,
         int pageSize = 10)
        {
            var result = await _checkoutRepository.GetCheckoutsAsync(
                searchUser,
                searchDate,
                searchBook,
                SearchStatus,
                pageNumber,
                pageSize);

            if (!result.Items.Any())
            {
                ViewBag.Message = "No checkouts found for the specified Search criteria you provide";
            }

            var totalPending = await _libraryDbContext.Checkouts
                .CountAsync(c => c.Status == CheckoutStatus.Pending);
            var totalOverdue = await _libraryDbContext.Checkouts
                .CountAsync(c => c.Status == CheckoutStatus.Overdue);
            var totalReturned = await _libraryDbContext.Checkouts
                .CountAsync(c => c.Status == CheckoutStatus.Returned);

            ViewData["searchUser"] = searchUser;
            ViewData["searchDate"] = searchDate;
            ViewData["searchBook"] = searchBook;
            ViewData["pageNumber"] = pageNumber;
            ViewData["pageSize"] = pageSize;
            ViewData["SearchStatus"] = SearchStatus;
            ViewData["TotalPending"] = totalPending;
            ViewData["TotalOverdue"] = totalOverdue;
            ViewData["TotalReturned"] = totalReturned;

            return View(result);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var checkout = await _checkoutRepository.GetCheckoutByIdAsync(id); 
            if (checkout == null)
            {
                return NotFound();
            }
            return View(checkout);
        }

      
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CheckoutDetailVM checkoutVM)
        {
            if (!ModelState.IsValid)
            {
                return View(checkoutVM);
            }

            try
            {
                bool isUpdated = await _checkoutRepository.UpdateCheckoutAsync(checkoutVM);
                if (isUpdated)
                {
                    ViewBag.SuccessMessage = "Checkout updated successfully.";
                }
                else
                {
                    ModelState.AddModelError("", "Checkout not found or could not be updated.");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error occurred: {ex.Message}");
            }

            return View(checkoutVM);
        }



        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var checkout = await _checkoutRepository.GetCheckoutByIdAsync(id);

            if (checkout == null)
            {
                ViewBag.ErrorMessage = "The checkout record could not be found.";
                return RedirectToAction("GetCheckouts");
            }

            var viewModel = new CheckoutDetailVM
            {
                Id = checkout.Id,
                UserName = checkout.UserName,
                BookName = checkout.BookName,
                DueDate = checkout.DueDate
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var isDeleted = await _checkoutRepository.DeleteCheckoutAsync(id);

            if (isDeleted)
            {
                ViewBag.SuccessMessage = "Checkout Deleted Successfully.";
            }
            else
            {
                ViewBag.ErrorMessage = "Checkout could not be deleted.";
            }

            var checkout = await _checkoutRepository.GetCheckoutByIdAsync(id);
            var viewModel = new CheckoutDetailVM
            {
                Id = id,
                UserName = checkout?.UserName ?? string.Empty,
                BookName = checkout?.BookName ?? string.Empty,
                DueDate = checkout?.DueDate ?? DateTime.Now 
            };

            return View("Delete", viewModel);
        }

    }

}

LibraryManagementSystem/Controllers/PenaltiesController.cs
using Application.Enums;
using Application.Interfaces;
using Application.Models;
using Application.ViewModels.Penalty;
using Infrastructure.Data;
using Infrastructure.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LibraryManagementSystem.Controllers
{
    public class PenaltiesController : Controller
    {
        private readonly IPenaltyRepository _penaltyRepository;
        private readonly ICheckoutRepository _checkoutRepository;
        private readonly UserManager<ApplicationUser> _userManager;

        public PenaltiesController(IPenaltyRepository penaltyRepository , ICheckoutRepository checkoutRepository , UserManager<ApplicationUser> userManager)
        {
            _penaltyRepository = penaltyRepository;
            _checkoutRepository = checkoutRepository; 
            _userManager = userManager;
        }

        public async Task<IActionResult> GetPenalites(
            int pageNumber=1,
            int pageSize=10,
            bool? isPaid = null,
            string username = null!,
            int? bookId = null,
            int? bookCopyId = null)
        {
            var result = await _penaltyRepository.GetAllPenaltiesPaginatedAsync(
            pageNumber,
            pageSize,
            isPaid,
           username,
            bookId, bookCopyId);

            if (!result.Items.Any())
            {
                ViewBag.Message = "No checkouts found for the specified Search criteria you provide";

            }
            var totalPaidPenalties = await _penaltyRepository.CountPenaltiesAsync(true); 
            var totalUnpaidPenalties = await _penaltyRepository.CountPenaltiesAsync(false); 

            ViewData["totalPaidPenalties"] = totalPaidPenalties;
            ViewData["totalUnpaidPenalties"] = totalUnpaidPenalties;
            ViewData["searchUser"] = username;
            ViewData["searchisPaid"] = isPaid;
            ViewData["searchBook"] = bookId;
            ViewData["searchbookCopy"] = bookCopyId;
            ViewData["pageNumber"] = pageNumber;
            ViewData["pageSize"] = pageSize;
          

            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> EditPenalty(int id)
        {
            var penalty = await _penaltyRepository.GetPenaltyByIdAsync(id);
            if (penalty == null)
            {
                return NotFound();
            }

            var viewModel = new EditPenaltyVM
            {
                Id = penalty.Id,
                Type = penalty.Type,
                Amount = penalty.Amount,
                IssuedDate = penalty.IssuedDate,
                IsPaid = penalty.IsPaid,
                PaidAt = penalty.PaidAt,
                PenaltyTypeList = new SelectList(Enum.GetValues(typeof(PenaltyType)))

            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditPenalty(EditPenaltyVM updatedPenaltyVM)
        {

            if (!ModelState.IsValid)
            {

                var modelErrors = string.Join(", ", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
                ModelState.AddModelError(string.Empty, $"Please correct the following errors: {modelErrors}");
                return View("EditPenalty", updatedPenaltyVM);
            }
            if (ModelState.IsValid)
            {
                var penaltyToUpdate = await _penaltyRepository.GetPenaltyByIdAsync(updatedPenaltyVM.Id);
                if (penaltyToUpdate == null)
                {
                    return NotFound();
                }

                penaltyToUpdate.Type = updatedPenaltyVM.Type;
                penaltyToUpdate.Amount = updatedPenaltyVM.Amount;
                penaltyToUpdate.IssuedDate = updatedPenaltyVM.IssuedDate;
                penaltyToUpdate.IsPaid = updatedPenaltyVM.IsPaid;
                penaltyToUpdate.PaidAt = updatedPenaltyVM.PaidAt;

                await _penaltyRepository.UpdatePenaltyAsync(penaltyToUpdate);

                TempData["Message"] = "Penalty updated successfully!";
                return RedirectToAction("GetPenalites");
            }

            return View(updatedPenaltyVM);
        }


        [HttpPost]
        public async Task<IActionResult> DeletePenalty(int id)
        {
            var penalty = await _penaltyRepository.GetPenaltyByIdAsync(id);
            if (penalty == null)
            {
                return NotFound();
            }

            await _penaltyRepository.DeletePenaltyAsync(id); 

            TempData["Message"] = "Penalty deleted successfully!";
            return RedirectToAction("GetPenalites");
        }

        [HttpGet]
        public async Task<IActionResult> MarkAsPaid(int penaltyId)
        {
            var result = await _penaltyRepository.MarkAsPaidAsync(penaltyId);

            if (!result)
            {
                TempData["ErrorMessage"] = "Penalty not found or could not be marked as paid.";
                return RedirectToAction("GetPenalites"); 
            }

            TempData["Message"] = "Penalty marked as paid successfully!";
            return RedirectToAction("GetPenalites");
        }

        [HttpGet]
        public IActionResult AddPenalty()
        {
            var viewModel = new AddPenaltyVM
            {
                Type = PenaltyType.LateReturn, 
                IsPaid = false, 
                PenaltyTypeList = new SelectList(Enum.GetValues(typeof(PenaltyType)))
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddPenalty(AddPenaltyVM penaltyVM)
        {
            var user = await _userManager.FindByNameAsync(penaltyVM.Username); 
            if (user == null)
            {
                ModelState.AddModelError("Username", "The specified username does not exist."); 
            }

            var checkout = await _checkoutRepository.GetCheckoutByIdAsync(penaltyVM.CheckoutId);
            if (checkout == null)
            {
                ModelState.AddModelError("CheckoutId", "The specified checkout ID does not exist.");
            }

            if (!ModelState.IsValid)
            {
                penaltyVM.PenaltyTypeList = new SelectList(Enum.GetValues(typeof(PenaltyType)));
                return View(penaltyVM);
            }

            await _penaltyRepository.AddPenaltyAsync(penaltyVM);
            TempData["Message"] = "Penalty added successfully!";
            return RedirectToAction("GetPenalites");
        }


    }
}

LibraryManagementSystem/Controllers/ReturnController.cs
using Application.Interfaces;
using Infrastructure.Data;
using Infrastructure.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LibraryManagementSystem.Controllers
{
    public class ReturnController : Controller
    {
       private readonly IReturnRepository _returnRepository;
        private readonly LibraryDbContext _libraryDbContext;


        public ReturnController(IReturnRepository returnRepository, LibraryDbContext libraryDbContext)
        {
            _returnRepository = returnRepository;
            _libraryDbContext = libraryDbContext;   
        }

        public async Task<IActionResult> GetReturns(
        string searchUser,
        DateTime? searchDueDate,
        DateTime? searchReturnDate,
        string searchBook,
         bool? isOverdue,
        int pageNumber = 1,
        int pageSize = 10)
        {
            var result = await _returnRepository.GetReturnsAsync(
                searchUser,
                searchDueDate,
                searchReturnDate,
                isOverdue,
                searchBook,
                pageNumber,
                pageSize);

            if (!result.Items.Any())
            {
                ViewBag.Message = "No returns found for the specified search criteria.";
            }

            var totalReturned = await _libraryDbContext.Returns.CountAsync();

            int overdueCount = result.Items.Count(r => r.IsOverdue);

            ViewData["searchUser"] = searchUser;
            ViewData["searchDueDate"] = searchDueDate;
            ViewData["searchReturnDate"] = searchReturnDate;
            ViewData["searchBook"] = searchBook;
            ViewData["pageNumber"] = pageNumber;
            ViewData["pageSize"] = pageSize;
            ViewData["TotalReturned"] = totalReturned;
            ViewData["OverdueCount"] = overdueCount;
            ViewData["isOverdue"] = isOverdue;

            return View(result);
        }

    }
}

LibraryManagementSystem/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    


    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="~/css//AdminDashboard.css">
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <!-- BOOTSTRAB -->
    <link rel="stylesheet" type="text/css"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />



</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <input type="checkbox" id="menu-toggle">
    <div class="sidebar">
        <div class="side-content">
            <div class="profile">
                <div class="profile-img bg-img" style="background-image: url('@Url.Content("~/Images/User/user (2).png")')"></div>
                <h4>Welcome Librarian</h4>
            </div>

            <div class="side-menu">
                <ul>
                    <li>
                    <a href="@Url.Action("AdminDashboard", "Account")" 
                       class="@(ViewContext.RouteData.Values["controller"].ToString() == "Account" && ViewContext.RouteData.Values["action"].ToString() == "AdminDashboard" ? "active" : "")">
                        <span class="las la-home"></span>
                        <small>Dashboard</small>
                    </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Book")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "Book" || ViewContext.RouteData.Values["controller"].ToString() == "BookCopy" ? "active" : "")">
                            <span class="las la-book"></span>
                            <small>Manage Books</small>
                        </a>
                    </li>


                    <li>
                        <a href="@Url.Action("Search", "MemberMangement")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "MemberMangement" && ViewContext.RouteData.Values["action"].ToString() == "Search" ? "active" : "")">
                            <span class="las la-users"></span>
                            <small>
                                Manage Members
                            </small>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("GetCheckouts", "Checkout")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "Checkout" && ViewContext.RouteData.Values["action"].ToString() == "GetCheckouts" ? "active" : "")">
                            <span class="las la-book-open"></span>
                            <small>Issue Book</small>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("GetReturns", "Return")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "Return" && ViewContext.RouteData.Values["action"].ToString() == "GetReturns" ? "active" : "")">
                            <span class="las la-undo"></span>
                            <small>Return Books</small>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("GetPenalites", "Penalties")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "Penalties" && ViewContext.RouteData.Values["action"].ToString() == "GetPenalites" ? "active" : "")">
                            <span class="las la-exclamation-circle"></span>
                            <small>Penalties</small>
                        </a>
                    </li>



                    <li>
                        <a href="@Url.Action("GetContacts", "ContactForm")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "ContactForm" && ViewContext.RouteData.Values["action"].ToString() == "GetContacts" ? "active" : "")">
                            <span class="las la-envelope"></span>
                            <small>Contacts</small>
                        </a>
                    </li>



                </ul>
            </div>
        </div>
    </div>

    <div class="main-content" >

        <header>
            <div class="header-content">
                <label for="menu-toggle">
                    <span class="las la-bars"></span>
                </label>

                <div class="user">
                    <span class="las la-power-off"></span>
                    <form id="logout-form" action="/Account/Logout" method="post" style="display: inline;">
                        <a href="#" onclick="event.preventDefault(); this.closest('form').submit();">Log out</a>
                    </form>
        </header>

    </div>

    @RenderSection("Scripts", required: false) 

</body>
</html>

LibraryManagementSystem/Views/Shared/MemberLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <title>Member Dashboard</title>
    <link rel="stylesheet" href="~/css//AdminDashboard.css">
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">

    <!-- BOOTSTRAB -->
    <link rel="stylesheet" type="text/css"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />



</head>
<body>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <input type="checkbox" id="menu-toggle">
    <div class="sidebar">
        <div class="side-content">
            <div class="profile">
                <div class="profile-img bg-img" style="background-image: url('@Url.Content("~/Images/User/user (2).png")')"></div>
                <h4>Welcome Member</h4>
            </div>

            <div class="side-menu">
                <ul>
                    <li>
                        <a href="@Url.Action("Profile", "MemberDashboard")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "MemberDashboard" && ViewContext.RouteData.Values["action"].ToString() == "Profile" ? "active" : "")">
                            <span class="las la-user-alt"></span>
                            <small>Profile</small>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("GetUserHistory", "MemberDashboard")"
                            class="@(ViewContext.RouteData.Values["controller"].ToString() == "MemberDashboard" && ViewContext.RouteData.Values["action"].ToString() == "GetUserHistory" ? "active" : "")">
                            <span class="las la-history"></span>
                            <small>History</small>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("GetUserPenalties", "MemberDashboard")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "MemberDashboard" && ViewContext.RouteData.Values["action"].ToString() == "GetUserPenalties" ? "active" : "")">
                            <span class="las la-exclamation-circle"></span>
                            <small>Penalties</small>
                        </a>
                    </li>


                    <li>
                        <a href="@Url.Action("Index", "MemberDashboard")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "MemberDashboard" && ViewContext.RouteData.Values["action"].ToString() == "Index" ? "active" : "")">
                            <span class="las la-book-open"></span>
                            <small>Books</small>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("GetWishlist", "MemberDashboard")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "MemberDashboard" && ViewContext.RouteData.Values["action"].ToString() == "GetWishlist" ? "active" : "")">
                            <span class="las la-heart"></span>  
                            <small>Wishlist</small>
                        </a>
                    </li>


                </ul>
            </div>
        </div>
    </div>

    <div class="main-content">

        <header>
            <div class="header-content">
                <label for="menu-toggle">
                    <span class="las la-bars"></span>
                </label>

                <div class="user">
                    <span class="las la-power-off"></span>
                    <form id="logout-form" action="/Account/Logout" method="post" style="display: inline;">
                        <a href="#" onclick="event.preventDefault(); this.closest('form').submit();">Log out</a>
                    </form>
                </div>

            </div>
        </header>

    </div>
    @RenderSection("Scripts", required: false)

</body>
</html>

LibraryManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryManagementSystem.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <!-- Boxicons CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <!-- BOOTSTRAP -->
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            fetch('/Book/GetNumberOfBooks')
                .then(response => response.json())
                .then(data => {
                    document.getElementById("bookCount").innerText = data;
                })
                .catch(error => {
                    console.error('Error fetching book count:', error);
                    document.getElementById("bookCount").innerText = "Error";
                });
        });
    </script>
</body>
</html>